// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/shops": {
    params: {};
  };
  "/shops/:id": {
    params: {
      "id": string;
    };
  };
  "/shops/:shopId/items/:itemId": {
    params: {
      "shopId": string;
      "itemId": string;
    };
  };
  "/brands": {
    params: {};
  };
  "/brands/:id": {
    params: {
      "id": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/news": {
    params: {};
  };
  "/news/:id": {
    params: {
      "id": string;
    };
  };
  "/share": {
    params: {};
  };
  "/share/:id": {
    params: {
      "id": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/auth/link-account": {
    params: {};
  };
  "/auth/mfa": {
    params: {};
  };
  "/auth/error": {
    params: {};
  };
  "/auth/setup-profile": {
    params: {};
  };
  "/share/new": {
    params: {};
  };
  "/share/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/mypage": {
    params: {};
  };
  "/mypage/security": {
    params: {};
  };
  "/mypage/favorites": {
    params: {};
  };
  "/mypage/contacts": {
    params: {};
  };
  "/mypage/notifications": {
    params: {};
  };
  "/mypage/profile/edit": {
    params: {};
  };
  "/mypage/account": {
    params: {};
  };
  "/mypage/share": {
    params: {};
  };
  "/mypage/share/drafts": {
    params: {};
  };
  "/mypage/share/bookmarks": {
    params: {};
  };
  "/listing-request": {
    params: {};
  };
  "/wishes": {
    params: {};
  };
  "/wishes/new": {
    params: {};
  };
  "/wishes/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/owner-application": {
    params: {};
  };
  "/owner-application/new": {
    params: {};
  };
  "/owner-application/:requestId": {
    params: {
      "requestId": string;
    };
  };
  "/owner": {
    params: {};
  };
  "/owner/shops/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/owner/shops/:id/brands": {
    params: {
      "id": string;
    };
  };
  "/owner/shops/:shopId/items": {
    params: {
      "shopId": string;
    };
  };
  "/owner/shops/:shopId/items/new": {
    params: {
      "shopId": string;
    };
  };
  "/owner/shops/:shopId/items/:itemId/edit": {
    params: {
      "shopId": string;
      "itemId": string;
    };
  };
  "/owner/shops/:shopId/wish-analytics": {
    params: {
      "shopId": string;
    };
  };
  "/owner/shops/:shopId/analytics": {
    params: {
      "shopId": string;
    };
  };
  "/owner/shops/:shopId/announcements": {
    params: {
      "shopId": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/shops": {
    params: {};
  };
  "/admin/shops/new": {
    params: {};
  };
  "/admin/shops/bulk": {
    params: {};
  };
  "/admin/shops/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/shops/:id/brands": {
    params: {
      "id": string;
    };
  };
  "/admin/brands": {
    params: {};
  };
  "/admin/applications": {
    params: {};
  };
  "/admin/contacts": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/news": {
    params: {};
  };
  "/admin/news/new": {
    params: {};
  };
  "/admin/news/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/analytics": {
    params: {};
  };
  "/admin/share-reports": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/shops" | "/shops/:id" | "/shops/:shopId/items/:itemId" | "/brands" | "/brands/:id" | "/contact" | "/terms" | "/privacy" | "/faq" | "/news" | "/news/:id" | "/share" | "/share/:id" | "/auth/login" | "/auth/register" | "/auth/callback" | "/auth/link-account" | "/auth/mfa" | "/auth/error" | "/auth/setup-profile" | "/share/new" | "/share/:id/edit" | "/mypage" | "/mypage/security" | "/mypage/favorites" | "/mypage/contacts" | "/mypage/notifications" | "/mypage/profile/edit" | "/mypage/account" | "/mypage/share" | "/mypage/share/drafts" | "/mypage/share/bookmarks" | "/listing-request" | "/wishes" | "/wishes/new" | "/wishes/:id/edit" | "/owner-application" | "/owner-application/new" | "/owner-application/:requestId" | "/owner" | "/owner/shops/:id/edit" | "/owner/shops/:id/brands" | "/owner/shops/:shopId/items" | "/owner/shops/:shopId/items/new" | "/owner/shops/:shopId/items/:itemId/edit" | "/owner/shops/:shopId/wish-analytics" | "/owner/shops/:shopId/analytics" | "/owner/shops/:shopId/announcements" | "/admin" | "/admin/shops" | "/admin/shops/new" | "/admin/shops/bulk" | "/admin/shops/:id/edit" | "/admin/shops/:id/brands" | "/admin/brands" | "/admin/applications" | "/admin/contacts" | "/admin/users" | "/admin/news" | "/admin/news/new" | "/admin/news/:id/edit" | "/admin/analytics" | "/admin/share-reports" | "/sitemap.xml" | "/*";
  };
  "pages/top/TopPage.tsx": {
    id: "pages/top/TopPage";
    page: "/";
  };
  "pages/shops/ShopsPage.tsx": {
    id: "pages/shops/ShopsPage";
    page: "/shops";
  };
  "routes/shop-detail.tsx": {
    id: "routes/shop-detail";
    page: "/shops/:id";
  };
  "pages/shops/ShopItemDetailPage.tsx": {
    id: "pages/shops/ShopItemDetailPage";
    page: "/shops/:shopId/items/:itemId";
  };
  "pages/brands/BrandSearchPage.tsx": {
    id: "pages/brands/BrandSearchPage";
    page: "/brands";
  };
  "routes/brand-detail.tsx": {
    id: "routes/brand-detail";
    page: "/brands/:id";
  };
  "pages/contact/ContactPage.tsx": {
    id: "pages/contact/ContactPage";
    page: "/contact";
  };
  "pages/legal/TermsPage.tsx": {
    id: "pages/legal/TermsPage";
    page: "/terms";
  };
  "pages/legal/PrivacyPolicyPage.tsx": {
    id: "pages/legal/PrivacyPolicyPage";
    page: "/privacy";
  };
  "pages/faq/FaqPage.tsx": {
    id: "pages/faq/FaqPage";
    page: "/faq";
  };
  "pages/news/NewsPage.tsx": {
    id: "pages/news/NewsPage";
    page: "/news";
  };
  "routes/news-detail.tsx": {
    id: "routes/news-detail";
    page: "/news/:id";
  };
  "pages/share/ShareTimelinePage.tsx": {
    id: "pages/share/ShareTimelinePage";
    page: "/share";
  };
  "routes/share-post-detail.tsx": {
    id: "routes/share-post-detail";
    page: "/share/:id";
  };
  "pages/auth/LoginPage.tsx": {
    id: "pages/auth/LoginPage";
    page: "/auth/login";
  };
  "pages/auth/RegisterPage.tsx": {
    id: "pages/auth/RegisterPage";
    page: "/auth/register";
  };
  "pages/auth/CallbackPage.tsx": {
    id: "pages/auth/CallbackPage";
    page: "/auth/callback";
  };
  "pages/auth/LinkAccountPage.tsx": {
    id: "pages/auth/LinkAccountPage";
    page: "/auth/link-account";
  };
  "pages/auth/MfaChallengePage.tsx": {
    id: "pages/auth/MfaChallengePage";
    page: "/auth/mfa";
  };
  "pages/auth/AuthErrorPage.tsx": {
    id: "pages/auth/AuthErrorPage";
    page: "/auth/error";
  };
  "routes/require-auth.tsx": {
    id: "routes/require-auth";
    page: "/auth/setup-profile" | "/share/new" | "/share/:id/edit" | "/mypage" | "/mypage/security" | "/mypage/favorites" | "/mypage/contacts" | "/mypage/notifications" | "/mypage/profile/edit" | "/mypage/account" | "/mypage/share" | "/mypage/share/drafts" | "/mypage/share/bookmarks" | "/listing-request";
  };
  "pages/auth/SetupProfilePage.tsx": {
    id: "pages/auth/SetupProfilePage";
    page: "/auth/setup-profile";
  };
  "pages/share/SharePostNewPage.tsx": {
    id: "pages/share/SharePostNewPage";
    page: "/share/new";
  };
  "pages/share/SharePostEditPage.tsx": {
    id: "pages/share/SharePostEditPage";
    page: "/share/:id/edit";
  };
  "pages/mypage/MyPage.tsx": {
    id: "pages/mypage/MyPage";
    page: "/mypage";
  };
  "pages/mypage/SecurityPage.tsx": {
    id: "pages/mypage/SecurityPage";
    page: "/mypage/security";
  };
  "pages/mypage/FavoritesPage.tsx": {
    id: "pages/mypage/FavoritesPage";
    page: "/mypage/favorites";
  };
  "pages/mypage/ContactsPage.tsx": {
    id: "pages/mypage/ContactsPage";
    page: "/mypage/contacts";
  };
  "pages/mypage/NotificationsPage.tsx": {
    id: "pages/mypage/NotificationsPage";
    page: "/mypage/notifications";
  };
  "pages/mypage/ProfileEditPage.tsx": {
    id: "pages/mypage/ProfileEditPage";
    page: "/mypage/profile/edit";
  };
  "pages/mypage/AccountPage.tsx": {
    id: "pages/mypage/AccountPage";
    page: "/mypage/account";
  };
  "pages/share/MySharesPage.tsx": {
    id: "pages/share/MySharesPage";
    page: "/mypage/share";
  };
  "pages/share/MyShareDraftsPage.tsx": {
    id: "pages/share/MyShareDraftsPage";
    page: "/mypage/share/drafts";
  };
  "pages/share/MyShareBookmarksPage.tsx": {
    id: "pages/share/MyShareBookmarksPage";
    page: "/mypage/share/bookmarks";
  };
  "pages/listing-request/ListingRequestPage.tsx": {
    id: "pages/listing-request/ListingRequestPage";
    page: "/listing-request";
  };
  "routes/require-wish.tsx": {
    id: "routes/require-wish";
    page: "/wishes" | "/wishes/new" | "/wishes/:id/edit";
  };
  "pages/wishes/WishesPage.tsx": {
    id: "pages/wishes/WishesPage";
    page: "/wishes";
  };
  "pages/wishes/WishNewPage.tsx": {
    id: "pages/wishes/WishNewPage";
    page: "/wishes/new";
  };
  "pages/wishes/WishEditPage.tsx": {
    id: "pages/wishes/WishEditPage";
    page: "/wishes/:id/edit";
  };
  "routes/require-owner-feature.tsx": {
    id: "routes/require-owner-feature";
    page: "/owner-application" | "/owner-application/new" | "/owner-application/:requestId";
  };
  "pages/owner-application/OwnerApplicationListPage.tsx": {
    id: "pages/owner-application/OwnerApplicationListPage";
    page: "/owner-application";
  };
  "pages/owner-application/OwnerApplicationNewPage.tsx": {
    id: "pages/owner-application/OwnerApplicationNewPage";
    page: "/owner-application/new";
  };
  "pages/owner-application/OwnerApplicationDMPage.tsx": {
    id: "pages/owner-application/OwnerApplicationDMPage";
    page: "/owner-application/:requestId";
  };
  "routes/require-owner.tsx": {
    id: "routes/require-owner";
    page: "/owner" | "/owner/shops/:id/edit" | "/owner/shops/:id/brands" | "/owner/shops/:shopId/items" | "/owner/shops/:shopId/items/new" | "/owner/shops/:shopId/items/:itemId/edit" | "/owner/shops/:shopId/wish-analytics" | "/owner/shops/:shopId/analytics" | "/owner/shops/:shopId/announcements";
  };
  "pages/owner/OwnerDashboardPage.tsx": {
    id: "pages/owner/OwnerDashboardPage";
    page: "/owner";
  };
  "pages/owner/OwnerShopEditPage.tsx": {
    id: "pages/owner/OwnerShopEditPage";
    page: "/owner/shops/:id/edit";
  };
  "routes/owner-shop-brands.tsx": {
    id: "routes/owner-shop-brands";
    page: "/owner/shops/:id/brands";
  };
  "pages/owner/ShopItemTypesPage.tsx": {
    id: "pages/owner/ShopItemTypesPage";
    page: "/owner/shops/:shopId/items";
  };
  "pages/owner/ShopItemNewPage.tsx": {
    id: "pages/owner/ShopItemNewPage";
    page: "/owner/shops/:shopId/items/new";
  };
  "pages/owner/ShopItemEditPage.tsx": {
    id: "pages/owner/ShopItemEditPage";
    page: "/owner/shops/:shopId/items/:itemId/edit";
  };
  "pages/owner/OwnerWishAnalyticsPage.tsx": {
    id: "pages/owner/OwnerWishAnalyticsPage";
    page: "/owner/shops/:shopId/wish-analytics";
  };
  "pages/owner/OwnerShopAnalyticsPage.tsx": {
    id: "pages/owner/OwnerShopAnalyticsPage";
    page: "/owner/shops/:shopId/analytics";
  };
  "pages/owner/OwnerShopAnnouncementsPage.tsx": {
    id: "pages/owner/OwnerShopAnnouncementsPage";
    page: "/owner/shops/:shopId/announcements";
  };
  "routes/require-admin.tsx": {
    id: "routes/require-admin";
    page: "/admin" | "/admin/shops" | "/admin/shops/new" | "/admin/shops/bulk" | "/admin/shops/:id/edit" | "/admin/shops/:id/brands" | "/admin/brands" | "/admin/applications" | "/admin/contacts" | "/admin/users" | "/admin/news" | "/admin/news/new" | "/admin/news/:id/edit" | "/admin/analytics" | "/admin/share-reports";
  };
  "pages/admin/AdminDashboardPage.tsx": {
    id: "pages/admin/AdminDashboardPage";
    page: "/admin";
  };
  "pages/admin/AdminShopsPage.tsx": {
    id: "pages/admin/AdminShopsPage";
    page: "/admin/shops";
  };
  "pages/admin/AdminShopNewPage.tsx": {
    id: "pages/admin/AdminShopNewPage";
    page: "/admin/shops/new";
  };
  "pages/admin/AdminShopBulkPage.tsx": {
    id: "pages/admin/AdminShopBulkPage";
    page: "/admin/shops/bulk";
  };
  "pages/admin/AdminShopEditPage.tsx": {
    id: "pages/admin/AdminShopEditPage";
    page: "/admin/shops/:id/edit";
  };
  "routes/admin-shop-brands.tsx": {
    id: "routes/admin-shop-brands";
    page: "/admin/shops/:id/brands";
  };
  "pages/admin/AdminBrandsPage.tsx": {
    id: "pages/admin/AdminBrandsPage";
    page: "/admin/brands";
  };
  "pages/admin/AdminApplicationsPage.tsx": {
    id: "pages/admin/AdminApplicationsPage";
    page: "/admin/applications";
  };
  "pages/admin/AdminContactsPage.tsx": {
    id: "pages/admin/AdminContactsPage";
    page: "/admin/contacts";
  };
  "pages/admin/AdminUsersPage.tsx": {
    id: "pages/admin/AdminUsersPage";
    page: "/admin/users";
  };
  "pages/admin/AdminNewsPage.tsx": {
    id: "pages/admin/AdminNewsPage";
    page: "/admin/news";
  };
  "pages/admin/AdminNewsNewPage.tsx": {
    id: "pages/admin/AdminNewsNewPage";
    page: "/admin/news/new";
  };
  "pages/admin/AdminNewsEditPage.tsx": {
    id: "pages/admin/AdminNewsEditPage";
    page: "/admin/news/:id/edit";
  };
  "pages/admin/AdminAnalyticsPage.tsx": {
    id: "pages/admin/AdminAnalyticsPage";
    page: "/admin/analytics";
  };
  "pages/admin/AdminShareReportsPage.tsx": {
    id: "pages/admin/AdminShareReportsPage";
    page: "/admin/share-reports";
  };
  "routes/sitemap.ts": {
    id: "routes/sitemap";
    page: "/sitemap.xml";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/top/TopPage": typeof import("./src/pages/top/TopPage.tsx");
  "pages/shops/ShopsPage": typeof import("./src/pages/shops/ShopsPage.tsx");
  "routes/shop-detail": typeof import("./src/routes/shop-detail.tsx");
  "pages/shops/ShopItemDetailPage": typeof import("./src/pages/shops/ShopItemDetailPage.tsx");
  "pages/brands/BrandSearchPage": typeof import("./src/pages/brands/BrandSearchPage.tsx");
  "routes/brand-detail": typeof import("./src/routes/brand-detail.tsx");
  "pages/contact/ContactPage": typeof import("./src/pages/contact/ContactPage.tsx");
  "pages/legal/TermsPage": typeof import("./src/pages/legal/TermsPage.tsx");
  "pages/legal/PrivacyPolicyPage": typeof import("./src/pages/legal/PrivacyPolicyPage.tsx");
  "pages/faq/FaqPage": typeof import("./src/pages/faq/FaqPage.tsx");
  "pages/news/NewsPage": typeof import("./src/pages/news/NewsPage.tsx");
  "routes/news-detail": typeof import("./src/routes/news-detail.tsx");
  "pages/share/ShareTimelinePage": typeof import("./src/pages/share/ShareTimelinePage.tsx");
  "routes/share-post-detail": typeof import("./src/routes/share-post-detail.tsx");
  "pages/auth/LoginPage": typeof import("./src/pages/auth/LoginPage.tsx");
  "pages/auth/RegisterPage": typeof import("./src/pages/auth/RegisterPage.tsx");
  "pages/auth/CallbackPage": typeof import("./src/pages/auth/CallbackPage.tsx");
  "pages/auth/LinkAccountPage": typeof import("./src/pages/auth/LinkAccountPage.tsx");
  "pages/auth/MfaChallengePage": typeof import("./src/pages/auth/MfaChallengePage.tsx");
  "pages/auth/AuthErrorPage": typeof import("./src/pages/auth/AuthErrorPage.tsx");
  "routes/require-auth": typeof import("./src/routes/require-auth.tsx");
  "pages/auth/SetupProfilePage": typeof import("./src/pages/auth/SetupProfilePage.tsx");
  "pages/share/SharePostNewPage": typeof import("./src/pages/share/SharePostNewPage.tsx");
  "pages/share/SharePostEditPage": typeof import("./src/pages/share/SharePostEditPage.tsx");
  "pages/mypage/MyPage": typeof import("./src/pages/mypage/MyPage.tsx");
  "pages/mypage/SecurityPage": typeof import("./src/pages/mypage/SecurityPage.tsx");
  "pages/mypage/FavoritesPage": typeof import("./src/pages/mypage/FavoritesPage.tsx");
  "pages/mypage/ContactsPage": typeof import("./src/pages/mypage/ContactsPage.tsx");
  "pages/mypage/NotificationsPage": typeof import("./src/pages/mypage/NotificationsPage.tsx");
  "pages/mypage/ProfileEditPage": typeof import("./src/pages/mypage/ProfileEditPage.tsx");
  "pages/mypage/AccountPage": typeof import("./src/pages/mypage/AccountPage.tsx");
  "pages/share/MySharesPage": typeof import("./src/pages/share/MySharesPage.tsx");
  "pages/share/MyShareDraftsPage": typeof import("./src/pages/share/MyShareDraftsPage.tsx");
  "pages/share/MyShareBookmarksPage": typeof import("./src/pages/share/MyShareBookmarksPage.tsx");
  "pages/listing-request/ListingRequestPage": typeof import("./src/pages/listing-request/ListingRequestPage.tsx");
  "routes/require-wish": typeof import("./src/routes/require-wish.tsx");
  "pages/wishes/WishesPage": typeof import("./src/pages/wishes/WishesPage.tsx");
  "pages/wishes/WishNewPage": typeof import("./src/pages/wishes/WishNewPage.tsx");
  "pages/wishes/WishEditPage": typeof import("./src/pages/wishes/WishEditPage.tsx");
  "routes/require-owner-feature": typeof import("./src/routes/require-owner-feature.tsx");
  "pages/owner-application/OwnerApplicationListPage": typeof import("./src/pages/owner-application/OwnerApplicationListPage.tsx");
  "pages/owner-application/OwnerApplicationNewPage": typeof import("./src/pages/owner-application/OwnerApplicationNewPage.tsx");
  "pages/owner-application/OwnerApplicationDMPage": typeof import("./src/pages/owner-application/OwnerApplicationDMPage.tsx");
  "routes/require-owner": typeof import("./src/routes/require-owner.tsx");
  "pages/owner/OwnerDashboardPage": typeof import("./src/pages/owner/OwnerDashboardPage.tsx");
  "pages/owner/OwnerShopEditPage": typeof import("./src/pages/owner/OwnerShopEditPage.tsx");
  "routes/owner-shop-brands": typeof import("./src/routes/owner-shop-brands.tsx");
  "pages/owner/ShopItemTypesPage": typeof import("./src/pages/owner/ShopItemTypesPage.tsx");
  "pages/owner/ShopItemNewPage": typeof import("./src/pages/owner/ShopItemNewPage.tsx");
  "pages/owner/ShopItemEditPage": typeof import("./src/pages/owner/ShopItemEditPage.tsx");
  "pages/owner/OwnerWishAnalyticsPage": typeof import("./src/pages/owner/OwnerWishAnalyticsPage.tsx");
  "pages/owner/OwnerShopAnalyticsPage": typeof import("./src/pages/owner/OwnerShopAnalyticsPage.tsx");
  "pages/owner/OwnerShopAnnouncementsPage": typeof import("./src/pages/owner/OwnerShopAnnouncementsPage.tsx");
  "routes/require-admin": typeof import("./src/routes/require-admin.tsx");
  "pages/admin/AdminDashboardPage": typeof import("./src/pages/admin/AdminDashboardPage.tsx");
  "pages/admin/AdminShopsPage": typeof import("./src/pages/admin/AdminShopsPage.tsx");
  "pages/admin/AdminShopNewPage": typeof import("./src/pages/admin/AdminShopNewPage.tsx");
  "pages/admin/AdminShopBulkPage": typeof import("./src/pages/admin/AdminShopBulkPage.tsx");
  "pages/admin/AdminShopEditPage": typeof import("./src/pages/admin/AdminShopEditPage.tsx");
  "routes/admin-shop-brands": typeof import("./src/routes/admin-shop-brands.tsx");
  "pages/admin/AdminBrandsPage": typeof import("./src/pages/admin/AdminBrandsPage.tsx");
  "pages/admin/AdminApplicationsPage": typeof import("./src/pages/admin/AdminApplicationsPage.tsx");
  "pages/admin/AdminContactsPage": typeof import("./src/pages/admin/AdminContactsPage.tsx");
  "pages/admin/AdminUsersPage": typeof import("./src/pages/admin/AdminUsersPage.tsx");
  "pages/admin/AdminNewsPage": typeof import("./src/pages/admin/AdminNewsPage.tsx");
  "pages/admin/AdminNewsNewPage": typeof import("./src/pages/admin/AdminNewsNewPage.tsx");
  "pages/admin/AdminNewsEditPage": typeof import("./src/pages/admin/AdminNewsEditPage.tsx");
  "pages/admin/AdminAnalyticsPage": typeof import("./src/pages/admin/AdminAnalyticsPage.tsx");
  "pages/admin/AdminShareReportsPage": typeof import("./src/pages/admin/AdminShareReportsPage.tsx");
  "routes/sitemap": typeof import("./src/routes/sitemap.ts");
  "routes/not-found": typeof import("./src/routes/not-found.tsx");
};